### PR TITLE
Remove kyverno apps that exist in default-apps-azure

### PR DESCRIPTION
**Pull request by fhielpos**
We added security-bundle to default-apps-azure. These apps for MCs will be managed by security-bundle in default-apps-azure. 

We upgraded all MCs to latest default-apps-azure so we can remove them from here.

### CODE REVIEW

**Review by fiunchinho — CHANGES_REQUESTED** [review]
You need to also remove the reference to the removed files https://github.com/giantswarm/capz-app-collection/blob/main/flux-manifests/kustomization.yaml#L30-L31

**Comment by erkanerol** [comment]
Please wait for this PR. We can merge this after bumping default-apps-azure for MCs, which is blocked by 1.25 upgrades. This is on my list.

**Comment by fhielpos** [comment]
Yeah, I realized this is only on gaggle and that it would break 😄 Won't merge yet.

**Comment by erkanerol** [comment]
@tuladhar I couldn't follow the last changes. Did we upgrade default-apps for all CAPZ MCs to the version that has security-bundle? If so, we can merge this.

**Comment by tuladhar** [comment]
> @tuladhar I couldn't follow the last changes. Did we upgrade default-apps for all CAPZ MCs to the version that has security-bundle? If so, we can merge this.

@erkanerol No, we haven't, we only upgraded till [v0.6.0](https://github.com/giantswarm/default-apps-azure/releases/tag/v0.6.0) with Teleport.

**Comment by erkanerol** [comment]
It seems @AverageMarcus  upgraded `gaggle` to fix something else. https://github.com/giantswarm/giantswarm-management-clusters/commit/f3d745eae720a3dd336fbcff3f1339b6d78594b8 

Let's keep `gaggle` broken for a few days. I hope we will sort it out.

**Comment by AverageMarcus** [comment]
Sorry, did I break something?

I needed to bump the observability-bundle to fix some of the issues with the E2E and conformance tests.

**Comment by erkanerol** [comment]
@AverageMarcus It is a complex topic. Don't worry about it. The customer asked us to support 1.25. We added security-bundle to default-apps to support 1.25 for WCs and WCs are OK now. However, we couldn't finish MC issues and we were avoiding upgrading defualt-apps for MCs. There is a conflict between collection apps and default apps now.

**Comment by AverageMarcus** [comment]
Ah sorry :(  I needed the prom stack fixed on the MC.

**Review by erkanerol — APPROVED** [review]

**Pull request merged**
